version: '3.7'
services:
  leads-micro-service:
    container_name: leads-micro-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./

  cadd:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-services
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/services
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
